export const GET_ADDRESS = 'GET_ADDRESS';

export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';

export const GET_TIMEZONE = 'GET_TIMEZONE';

export const GET_TIMEZONE_SUCCESS = 'GET_TIMEZONE_SUCCESS';

export const REQUEST_FAILURE = 'REQUEST_FAILURE';
